[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "flights-api"
version = "0.1.0"
description = "Flight search API"
requires-python = ">=3.12"
dependencies = [
  "fastapi>=0.104.1",
  "uvicorn>=0.24.0",
  "pydantic>=2.5.2",
  "python-multipart>=0.0.6",
  "aiohttp>=3.9.1",
  "brotli>=1.1.0",
  "selectolax>=0.3.17",
  "python-dateutil>=2.8.2",
]

[project.optional-dependencies]
test = [
  "pytest>=7.4.3",
  "pytest-asyncio>=0.21.1",
  "pytest-cov>=4.1.0",
  "httpx>=0.25.2",
]

[tool.hatch.build.targets.wheel]
packages = ["src/api"]

[tool.pytest.ini_options]
testpaths = ["src/api/tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --cov=api --cov-report=term-missing"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
filterwarnings = [
  "ignore::DeprecationWarning:google._upb._message",
  "ignore::DeprecationWarning:google.protobuf",
  "ignore::DeprecationWarning:importlib._bootstrap",
  "ignore::DeprecationWarning:pytest_asyncio.plugin",
]

[tool.coverage.run]
source = ["src/api"]
omit = ["src/api/tests/*"]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "if TYPE_CHECKING:",
  "raise NotImplementedError",
]

[dependency-groups]
dev = [
    "pandas>=2.2.3",
]
