"""Initial migration

Revision ID: b5a99a358851
Revises: 
Create Date: 2024-12-23 13:29:42.846734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5a99a358851'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flight_results', 'outbound_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('flight_results', 'return_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('flight_results', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('flight_results', 'current_price_indicator',
               existing_type=postgresql.ENUM('low', 'typical', 'high', name='price_indicator'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('flight_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_flight_results_job_id', table_name='flight_results')
    op.drop_index('idx_flight_results_price', table_name='flight_results')
    op.alter_column('jobs', 'status',
               existing_type=postgresql.ENUM('pending', 'running', 'completed', 'failed', name='job_status'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::job_status"))
    op.alter_column('jobs', 'best_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_jobs_status', table_name='jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_jobs_status', 'jobs', ['status'], unique=False)
    op.alter_column('jobs', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('jobs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('jobs', 'best_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('jobs', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('pending', 'running', 'completed', 'failed', name='job_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::job_status"))
    op.create_index('idx_flight_results_price', 'flight_results', ['price'], unique=False)
    op.create_index('idx_flight_results_job_id', 'flight_results', ['job_id'], unique=False)
    op.alter_column('flight_results', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('flight_results', 'current_price_indicator',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('low', 'typical', 'high', name='price_indicator'),
               existing_nullable=False)
    op.alter_column('flight_results', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('flight_results', 'return_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('flight_results', 'outbound_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###